const assert=require('node:assert/strict');
const M=require('../lbnb-v0-live-07/site/journey-model.js');
const objects=[{id:'a',title:'Alfama',type:'place',destination:'Lisbon',area:'Alfama',tags:['architecture']},{id:'context',title:'Fado',type:'story',destination:'Lisbon'},{id:'b',title:'Baixa',type:'place',destination:'Lisbon',area:'Baixa'},{id:'c',title:'Belem',type:'place',destination:'Lisbon',area:'Belem'},{id:'d',title:'Museum',type:'place',destination:'Lisbon',tags:['architecture']},{id:'stay',title:'Roof',type:'place',subtype:'stay',destination:'Lebanon'}];
const source={suggestionId:'source',destination:'Lisbon',title:'Stone, Sound & River',nodes:[{object_id:'a',time:'09:30'},{object_id:'context',role:'context'},{object_id:'b',time:'12:00'},{object_id:'c',time:'14:00'}]};
const snapshot=JSON.stringify(source),s=M.empty(),a=M.createJourney(s,source),b=M.createJourney(s,source);
assert.notEqual(a.journeyId,b.journeyId);assert.notEqual(a.items[0].journeyItemId,b.items[0].journeyItemId);
M.setDates(s,a.journeyId,'2026-10-02','2026-10-06');assert.equal(b.startDate,'');assert.equal(JSON.stringify(source),snapshot);
assert.equal(M.projection(s,a).days.length,5);
assert.equal(M.projection(s,a).days[0].items[1].sourceId,'context');
const first=a.items[0];M.move(s,a.journeyId,first.journeyItemId,2);
assert.ok(M.projection(s,a).days[2].items.some(i=>i.sourceId==='a'));
M.move(s,a.journeyId,a.items[1].journeyItemId,2,first.journeyItemId);
assert.ok(M.projection(s,a).days[2].items.findIndex(i=>i.sourceId==='context')<M.projection(s,a).days[2].items.findIndex(i=>i.sourceId==='a'));
first.mode='fixed';assert.throws(()=>M.move(s,a.journeyId,first.journeyItemId,1),/fixed/);
M.move(s,a.journeyId,first.journeyItemId,1,null,{deliberate:true});assert.equal(first.dayIndex,1);
assert.throws(()=>M.setDates(s,a.journeyId,'2026-02-30','2026-03-02'),/valid/);
assert.throws(()=>M.setDates(s,a.journeyId,'2026-10-10','2026-10-02'),/valid/);
M.setDates(s,b.journeyId,'2026-11-01','2026-11-03');assert.equal(a.startDate,'2026-10-02');
const event={bookingId:'bk',listingId:'b',destination:'Lisbon',kind:'experience',start:'2026-10-03',end:'2026-10-03',startTime:'20:30',status:'planned'};
s.bookings.push(event);const bi=M.attachBooking(s,'bk',a.journeyId);
M.attachBooking(s,'bk',a.journeyId);assert.equal(a.items.filter(i=>i.bookingId==='bk').length,1);
assert.equal(event.journeyItemId,bi.journeyItemId);
assert.throws(()=>M.attachBooking(s,'bk',b.journeyId),/Detach/);
assert.throws(()=>M.updateBooking(s,'bk',{status:'confirmed'}),/connected host/);
M.updateBooking(s,'bk',{status:'pending'},{hostEvent:true});M.updateBooking(s,'bk',{status:'confirmed'},{hostEvent:true});
assert.equal(M.projection(s,a).days[1].items.find(i=>i.bookingId==='bk').fixed,true);
M.updateBooking(s,'bk',{start:'2026-10-20',end:'2026-10-20'},{hostEvent:true});
assert.equal(M.projection(s,a).outside[0].booking.bookingId,'bk');
M.detachBooking(s,'bk');assert.equal(event.journeyId,null);assert.equal(a.items.some(i=>i.bookingId==='bk'),false);
const lebanon=M.createJourney(s,{destination:'Lebanon',items:[]});M.setDates(s,lebanon.journeyId,'2026-10-02','2026-10-06');
const stay={bookingId:'stay1',listingId:'stay',destination:'Lebanon',kind:'stay',start:'2026-10-02',end:'2026-10-06',status:'planned'};
const stay2={...stay,bookingId:'stay2',start:'2026-12-01',end:'2026-12-05'};
s.bookings.push(stay,stay2);M.attachBooking(s,'stay1',lebanon.journeyId);
const p=M.projection(s,lebanon);assert.equal(p.spans.length,1);assert.equal(p.days.flatMap(d=>d.items).length,0);assert.equal(p.days.filter(d=>d.stayEvents.some(e=>e.night)).length,4);
assert.equal(p.days[4].stayEvents[0].phase,'Check-out');assert.equal(s.bookings.filter(x=>x.listingId==='stay').length,2);
assert.throws(()=>M.attachBooking(s,'stay2',a.journeyId),/destination/);
const jSnapshot=JSON.stringify(s.journeys);
const suggestion=M.suggest(s,objects,['d'],'Lisbon');assert.ok(suggestion.items.some(i=>i.sourceId==='d'));assert.ok(suggestion.context.bookingIds.includes('bk'));
assert.equal(JSON.stringify(s.journeys),jSnapshot);assert.equal(JSON.stringify(source),snapshot);
const migrated=M.migrate({plan:{planned:true,start_date:'2026-10-02',end_date:'2026-10-06'},bookings:[{id:'old',object_id:'stay',date:'2026-10-02',end_date:'2026-10-06',status:'planned'}],replacements:{a:'d'},order:{normal:['a','context','b','c']}},source,objects);
assert.equal(migrated.journeys.length,1);assert.equal(migrated.journeys[0].items.find(i=>i.sourceId==='d').sourceId,'d');
assert.equal(migrated.bookings[0].bookingId,'old');assert.equal(migrated.bookings[0].journeyId,null);
assert.equal(M.migrate({plan:{planned:false}},source,objects).journeys.length,0);
assert.equal(M.dates('2026-03-28','2026-03-31').length,4,'date allocation is stable across DST');
console.log('PASS: independent Journey copies and dates; day allocation and within/cross-day moves; fixed items; identity-linked bookings and host transitions; stay nights; migration; contextual suggestion isolation.');
