const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://**/*',r=>r.abort());
 await page.goto(process.env.NAVA_TEST_URL||'http://127.0.0.1:8765/');
 await page.waitForFunction(()=>typeof data!=='undefined'&&data&&window.NAVA_VERSION==='1.6.1');
 await page.evaluate(()=>openDatePicker());
 assert.equal(await page.locator('.rangePicker').count(),1);
 await page.evaluate(()=>{writePlan({planned:true,start_date:'',end_date:''});openJourney('edit')});
 assert.match(await page.locator('#journeyContent').innerText(),/Dates undecided/);
 const stay=await page.evaluate(()=>data.objects.find(o=>o.subtype==='stay').id);
 await page.evaluate(id=>{openObject(obj(id));openBookingSheet(obj(id))},stay);
 await page.locator('#bookingStart').fill('2026-10-05');
 await page.locator('#bookingEnd').fill('2026-10-07');
 await page.locator('#saveBooking').click();
 assert.equal(await page.evaluate(()=>readBookings()[0].status),'planned');
 assert.match(await page.locator('.bookingPanel').innerText(),/No request has been sent/);
 await page.evaluate(()=>openJourney('edit'));
 assert.equal(await page.locator('[data-node-key^="anchor-"]').count(),0,'Lebanon Stay must not be a Lisbon anchor');
 await page.evaluate(id=>openBookingSheet(obj(id)),stay);
 await page.locator('#bookingEnd').fill('2026-10-05');
 await page.locator('#saveBooking').click();
 assert.equal(await page.locator('#actionSheet').isVisible(),true);
 assert.equal(await page.evaluate(()=>readBookings()[0].end_date),'2026-10-07');
 await page.locator('#bookingCancel').click();
 await page.evaluate(()=>{closeSheet();$('journeyView').hidden=true;openReelFullscreen(document.querySelector('#feed .reel'))});
 const first=await page.locator('#reelFullscreenContent .reel').getAttribute('data-reel');
 await page.evaluate(()=>stepFullscreen(1));
 assert.notEqual(await page.locator('#reelFullscreenContent .reel').getAttribute('data-reel'),first);
 assert.equal(await page.locator('#reelFullscreenContent .rail').isVisible(),true);
 await page.evaluate(()=>closeReelFullscreen());
 await page.reload();await page.waitForFunction(()=>data&&window.NAVA_VERSION);
 assert.equal(await page.evaluate(()=>readBookings()[0].end_date),'2026-10-07');
 await page.evaluate(()=>{localStorage.setItem(BOOKINGS_KEY,'{}');localStorage.setItem(SAVED_KEY,'{}')});
 assert.deepEqual(await page.evaluate(()=>readBookings()),[]);
 assert.deepEqual(await page.evaluate(()=>readSaved()),[]);
 await page.evaluate(()=>openDatePicker());
 await page.screenshot({path:'/tmp/nava-v16-calendar.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: mobile range calendar, dates undecided, stay validation, personal-plan status, destination anchors, fullscreen navigation/carousel, persistence, malformed storage, no runtime errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
