const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 const engine=process.env.NAVA_BROWSER||'chromium',browser=await({chromium,webkit}[engine]).launch({headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://**/*',r=>r.abort());
 await page.goto(process.env.NAVA_TEST_URL||'http://127.0.0.1:8765/');
 await page.waitForFunction(()=>typeof data!=='undefined'&&data&&window.NAVA_VERSION==='1.6.2'&&workspace162);
 await page.waitForTimeout(300);
 const card=page.locator('#feed .card').first(),cardId=await card.getAttribute('data-object');
 await card.click();await page.locator('#saveObject').click();assert.equal(await page.evaluate(id=>readSaved().includes(id),cardId),true);
 await page.evaluate(()=>closeSheet());
 const recovered=await page.evaluate(()=>data.objects.filter(o=>o.subtype==='stay'&&o.image?.startsWith('./media/listings/')).map(o=>o.id));
 assert.ok(recovered.length>=70);await page.evaluate(id=>openObject(obj(id)),recovered[0]);
 await page.waitForFunction(()=>{const im=document.querySelector('.sheetHero img');return im?.complete&&im.naturalWidth>0});
 await page.locator('.sheetHero').click({position:{x:100,y:80}});
 await page.waitForFunction(()=>{const im=$('mediaViewerImg');return !im.hidden&&im.complete&&im.naturalWidth>0});
 await page.evaluate(()=>{closeMediaViewer();closeSheet();openExplore()});
 const initial=await page.locator('#exploreGrid .stayCard').count();assert.equal(initial,16);
 await page.evaluate(()=>{$('exploreView').scrollTop=$('exploreView').scrollHeight});
 await page.waitForFunction(()=>document.querySelectorAll('#exploreGrid .stayCard').length>16);
 assert.doesNotMatch(await page.locator('#exploreGrid').innerText(),/remaining/);
 await page.evaluate(()=>{$('exploreSearch').value='Bayt Nawal';renderExplore();$('exploreView').scrollTop=0});
 await page.waitForFunction(()=>{const im=document.querySelector('#exploreGrid img');return im?.complete&&im.naturalWidth>0});
 const seam=await page.locator('#exploreGrid .stayVisual').first().evaluate(el=>{const im=el.querySelector('img'),a=el.getBoundingClientRect(),b=im.getBoundingClientRect(),cs=getComputedStyle(im);return{dx:Math.abs(a.x-b.x),dy:Math.abs(a.y-b.y),dw:Math.abs(a.width-b.width),dh:Math.abs(a.height-b.height),fit:cs.objectFit,display:cs.display,overflow:getComputedStyle(el).overflow}});
 assert.ok([seam.dx,seam.dy,seam.dw,seam.dh].every(x=>x<.1));assert.equal(seam.fit,'cover');assert.equal(seam.display,'block');assert.equal(seam.overflow,'hidden');
 await page.screenshot({path:'/tmp/nava-'+engine+'-explorer.png'});
 await page.evaluate(()=>{writeSaved(['alfama','rossio-baixa','belem']);openMy('saved')});
 const centre=await page.locator('[data-remove]').first().evaluate(el=>{const a=el.getBoundingClientRect(),b=el.querySelector('svg').getBoundingClientRect();return{width:a.width,height:a.height,x:Math.abs(a.x+a.width/2-b.x-b.width/2),y:Math.abs(a.y+a.height/2-b.y-b.height/2)}});
 assert.equal(centre.width,35);assert.equal(centre.height,35);assert.ok(centre.x<.1&&centre.y<.1);
 await page.screenshot({path:'/tmp/nava-'+engine+'-saved.png'});
 const original=await page.evaluate(()=>JSON.stringify(data.journeys));
 await page.evaluate(()=>openMy('journeys'));await page.locator('[data-use-suggestion]').first().click();
 await page.locator('#undated162').click();
 const first=await page.evaluate(()=>owned162().journeyId);
 await page.locator('#journeyDatesBadge').click();await page.locator('#chooseDates162').click();
 await page.locator('#journeyStartInput').fill('2026-10-02');await page.locator('#journeyEndInput').fill('2026-10-06');await page.locator('#saveJourneyDate').click();
 assert.equal(await page.locator('.day162').count(),5);await page.locator('#editTimeline162').click();
 const iid=await page.evaluate(()=>owned162().items[0].journeyItemId);
 const handle=page.locator('[data-item="'+iid+'"] .handle162');await handle.scrollIntoViewIfNeeded();
 await page.evaluate(()=>{$('journeyView').scrollTop=document.querySelector('[data-day="0"]').offsetTop-120});
 const h=await handle.boundingBox(),drop=await page.locator('[data-day="1"] .dayNode162').boundingBox();
 await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();
 await page.mouse.move(h.x+h.width/2,drop.y+drop.height/2,{steps:16});await page.waitForTimeout(180);await page.mouse.up();
 assert.equal(await page.evaluate(id=>owned162().items.find(i=>i.journeyItemId===id).dayIndex,iid),1,'pointer dragging moves to another day');
 await page.locator('[data-item="'+iid+'"] [data-edit-item]').click();
 await page.locator('#itemDay162').selectOption('2');await page.locator('#itemTime162').fill('10:15');await page.locator('#saveItem162').click();
 assert.equal(await page.locator('[data-day="2"] [data-item="'+iid+'"]').count(),1);
 await page.screenshot({path:'/tmp/nava-'+engine+'-timeline.png',fullPage:true});
 await page.locator('[data-zoom-day="2"]').click();assert.equal(await page.locator('.day162').count(),1);
 await page.locator('#tripZoom162').click();assert.equal(await page.locator('.day162').count(),5);
 await page.locator('[data-jview="itinerary"]').click();assert.equal(await page.locator('[data-day="2"] [data-item="'+iid+'"]').count(),1);
 await page.screenshot({path:'/tmp/nava-'+engine+'-itinerary.png'});
 await page.locator('[data-jview="calendar"]').click();assert.equal(await page.locator('.journeyEvent').count(),5);assert.ok(await page.locator('.calDay').evaluateAll(xs=>xs.every(x=>x.getBoundingClientRect().height<120)),'calendar rows stay compact');
 await page.screenshot({path:'/tmp/nava-'+engine+'-calendar.png'});
 await page.locator('[data-jview="map"]').click();assert.match(await page.locator('#journeyContent').innerText(),/Day 3/);
 await page.evaluate(()=>openMy('journeys'));await page.locator('[data-use-suggestion]').first().click();await page.locator('#undated162').click();
 const second=await page.evaluate(()=>owned162().journeyId);assert.notEqual(first,second);
 await page.evaluate(id=>openOwned162(id),first);assert.equal(await page.evaluate(()=>owned162().startDate),'2026-10-02');
 assert.equal(await page.evaluate(()=>JSON.stringify(data.journeys)),original);
 await page.evaluate(()=>{openMy('bookings');openBookingSheet(data.objects.find(o=>o.subtype==='stay'))});
 await page.locator('#bookingStart').fill('2026-10-02');await page.locator('#bookingEnd').fill('2026-10-06');await page.locator('#saveBooking').click();
 const bid=await page.evaluate(()=>workspace162.bookings[0].bookingId);
 assert.equal(await page.evaluate(()=>workspace162.bookings[0].journeyId),null);
 await page.evaluate(()=>{const b=workspace162.bookings[0];const j=M162.createJourney(workspace162,{destination:b.destination,items:[]},{title:'Lebanon October'});M162.setDates(workspace162,j.journeyId,'2026-10-02','2026-10-06');M162.attachBooking(workspace162,b.bookingId,j.journeyId);persist162();openOwned162(j.journeyId)});
 assert.equal(await page.locator('.staySpan162').count(),1);assert.equal(await page.locator('.stayEvent162').count(),2);assert.equal(await page.locator('.node162').count(),0);
 await page.evaluate(id=>{NavaHostEvents.apply({bookingId:id,status:'pending'});NavaHostEvents.apply({bookingId:id,status:'confirmed'})},bid);
 assert.match(await page.locator('.staySpan162').innerText(),/Confirmed/i);
 await page.evaluate(()=>openMy('bookings'));assert.match(await page.locator('[data-booking-card="'+bid+'"]').innerText(),/Confirmed/i);
 await page.evaluate(()=>openBookingSheet(obj(workspace162.bookings[0].listingId)));
 await page.locator('#bookingStart').fill('2026-12-02');await page.locator('#bookingEnd').fill('2026-12-06');await page.locator('#saveBooking').click();
 assert.equal(await page.evaluate(()=>workspace162.bookings.length),2);
 const journeysBefore=await page.evaluate(()=>JSON.stringify(workspace162.journeys));
 await page.evaluate(()=>generateSuggestion162('Lisbon'));assert.equal(await page.evaluate(()=>JSON.stringify(workspace162.journeys)),journeysBefore);
 await page.reload();await page.waitForFunction(()=>typeof workspace162!=='undefined'&&workspace162);
 assert.equal(await page.evaluate(()=>workspace162.journeys.length),3);assert.equal(await page.evaluate(()=>workspace162.bookings.length),2);
 await page.evaluate(()=>{localStorage.removeItem(JOURNEYS_V2_KEY);localStorage.setItem(PLAN_KEY,JSON.stringify({planned:true,start_date:'2026-10-02',end_date:'2026-10-06'}));localStorage.setItem(PLANNED_KEY,'1');localStorage.setItem(BOOKINGS_KEY,'[]')});
 await page.reload();await page.waitForFunction(()=>workspace162?.journeys.length===1);await page.reload();await page.waitForFunction(()=>workspace162?.journeys.length===1);
 assert.deepEqual(errors,[]);
 fs.writeFileSync('/tmp/nava-'+engine+'-report.json',JSON.stringify({engine,recoveredStays:recovered.length,seam,centre,runtimeErrors:errors,checks:'progressive loading, independent journeys, dates, pointer drag, zoom, projections, stay spans, host event projection, repeat booking, suggestion isolation, reload, migration'},null,2));
 console.log('PASS '+engine+': mobile geometry, photos, infinite loading, centred SVG, Journey independence, day drag and zoom, all projections, bookings and stays, migration and persistence.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
